### ISSUE TITLE
Groupe Capstone project :100: 

### ISSUE THREAD

**Issue by Said-laasri** [Said-laasri/Capstone--Kanban-board#22]
<img src="https://media1.giphy.com/media/kIRSvV2IKk0UN0Rb8l/giphy.gif"/>
Our group is consist of two people @kelwilson and @Said-laasri .

[The link for the project](https://github.com/Said-laasri/Capstone--Kanban-board )

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- Descriptive information ✔️
- Tasks are distributed equally ✔️

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly assign all tasks in your project as per this [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the%20team%20members%20should%20assign%20themselves%20to%20the%20correct%20cards.%20Decide%20who%20will%20be%20the%20assignee%20for%20the%20cards%20marked%20as%20group%20tasks.%20All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees.). Now the group tasks aren't assigned to anyone.
![image](https://user-images.githubusercontent.com/24703171/180793711-61158522-9723-44cc-8196-23d3001513c9.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lordkaito** [comment]
Hi @Said-laasri, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
